### ISSUE TITLE
RELEASE1: Tracking Issue

### ISSUE THREAD

**Issue by twilson63** [chscodecamp/CODEcampAS#7]
Progress:

- [ ] - [Index.md](/chscodecamp/CODEcampAS/blob/master/index.md)
- [ ] - [1-hello-world](/chscodecamp/CODEcampAS/blob/master/1-hello-world)
  - [ ] - [index.md](/chscodecamp/CODEcampAS/blob/master/1-hello-world/index.md)
  - [ ] - [demo.md](/chscodecamp/CODEcampAS/blob/master/1-hello-world/demo.md)
  - [ ] - [1.md](/chscodecamp/CODEcampAS/blob/master/1-hello-world/1.md)
  - [ ] - [2.md](/chscodecamp/CODEcampAS/blob/master/1-hello-world/2.md)
  - [ ] - [3.md](/chscodecamp/CODEcampAS/blob/master/1-hello-world/3.md)
  - [ ] - [4.md](/chscodecamp/CODEcampAS/blob/master/1-hello-world/4.md)
- [ ] - [2-first-web-site](/chscodecamp/CODEcampAS/blob/master/2-first-web-site)
  - [ ] - [index.md](/chscodecamp/CODEcampAS/blob/master/2-first-web-site/index.md)
  - [ ] - [name.md](/chscodecamp/CODEcampAS/blob/master/2-first-web-site/name.md)
  - [ ] - [story.md](/chscodecamp/CODEcampAS/blob/master/2-first-web-site/story.md)
  - [ ] - [powers.md](/chscodecamp/CODEcampAS/blob/master/2-first-web-site/powers.md)
  - [ ] - [avatar.md](/chscodecamp/CODEcampAS/blob/master/2-first-web-site/avatar.md)
  - [ ] - [css-colors.md](/chscodecamp/CODEcampAS/blob/master/2-first-web-site/css-colors.md)
  - [ ] - [layout.md](/chscodecamp/CODEcampAS/blob/master/2-first-web-site/layout.md)
  - [ ] - [ids-and-classes.md](/chscodecamp/CODEcampAS/blob/master/2-first-web-site/ids-and-classes.md)
  - [ ] - [animation.md](/chscodecamp/CODEcampAS/blob/master/2-first-web-site/animation.md)

**Comment by twilson63** [comment]
@rwcrosby @bryanchappell 

Updated the maze-game

**Comment by twilson63** [comment]
@rwcrosby @bryanchappell

Posted first draft of the Magic Button, still needs work, but I have some to review.

Current thinking is to re name project to Magic Button instead of Magic Eight Ball - http://codecampkids.cfapps.io/4-magic-eight-ball/

**Comment by twilson63** [comment]
Updated Project 5, still needs a lot of fine tuning, but the meat is there.

**Comment by twilson63** [comment]
@rwcrosby @bryanchappell 

Updated 7 snake game
